### ISSUE TITLE
Unknown ping targets aren't reported

### ISSUE THREAD

**Issue by chrisbartley** [CMU-CREATE-Lab/statping#1]
I have statping installed and running on my cpb-backups server, and added records in the spreadsheet to ping the various VOC monitors in the lab.  Since our router uses DHCP and we don't have IP address reservation set up for the VOC monitors, I didn't want to rely on the monitors always having the same IP address.  So I referenced them in the spreadsheet using their .local Bonjour/Avahi name.  Which works great for monitors which are alive and responding to pings.  But monitors which are down cause an error like this in statping's log:

```
Stat.log critical statping cpb-backups Exception countPings could not parse response: ping: voc0041.local: Name or service not known
 while monitoring VOC0041 None
```

...that's understandable, but those monitors are apparently not getting reported up to stat.createlab.org.  We have four such monitors right now, but if you just look at stat.createlab.org it appears that there are no problems.

**Comment by rsargent** [comment]
Thanks Chris for the report.  I believe I fixed it, and pushed to github.

(FWIW the exceptions were logged in the "statping" section of stat -- not a
super-helpful status display, but worth knowing where the diagnostics are
if there are new mysteries in the future)

**Comment by rsargent** [comment]
Oh, sorry, I read more closely and you did note the statping log :-)
thanks again

**Comment by chrisbartley** [comment]
Ah! Neat, I didn't even notice there was a statping section of stat.  The log I was referencing is the `statping.ipynb.log` file on the cpb-backups machine. Anyway, thanks!
